[build]
  publish = "_site"
  command = "eleventy"

[[redirects]]
  from = "/*"
  to = "/"

[[redirects]]
  from = "/"
  to = "/tw"
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/en"
  to = "/"
  status = 200

