[build]
  publish = "_site"
  command = "eleventy"

[[redirects]]
  from = "/*"
  to = "/tw"
  status = 404

[[redirects]]
  from = "/*"
  to = "/"

[[redirects]]
  from = "/old-path"
  to = "/new-path"