[build]
  publish = "_site"
  command = "eleventy"

[[redirects]]
  from = "/*"
  to = "/tw"
  status = 200
  conditions = {Language = ["en"], Country = ["US"]}

[[redirects]]
  from = "/*"
  to = "/"

[[redirects]]
  from = "/old-path"
  to = "/new-path"